Создание UserModule
onebytecode/krugozor-iOSVisitors pull request #5
Opened 2017-09-27 14:32 UTC by KuDji

Добавлена модель для CoreData. Добавлена модель UserModule

2017-09-27 14:37 UTC, danilinAlex commented
А где Core Data?

2017-09-27 14:40 UTC, KuDji commented
Где?

2017-09-28 07:14 UTC, danilinAlexexander requested changes
Попробуем мол, нужны изменения

2017-09-28 09:49 UTC, danilinAlexexander submitted a review, later dismissed

2017-09-28 10:17 UTC, closed without merging